#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [ "$1" = "" ]
then
  echo "Usage: $0 track-stems-folder"
  echo "Stems folder should contain info.txt and stems-0.wav...stems-X.wav"
else
  fullpath=`readlink -f "${1}"`
  pd -batch -send "load-track ${fullpath}" $DIR/_main.pd $DIR/_record.pd
fi
